aggregator/aggregator/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('service.urls')),
    url(r'^api/', include('service.api_urls')),
    url(r'^admin/', admin.site.urls),
]

aggregator/service/urls.py
from django.conf.urls import url

from . import views

app_name = 'service'
urlpatterns = [
    # url('^$', views.View.as_view()),
    url('^user/(?P<user_login>.+)/quest/(?P<quest_id>[0-9]+)/place/(?P<place_id>[0-9]+)/fact/(?P<fact_id>[0-9]+)/$',
        views.UiPlaceInfoView.as_view()),
    url('^user/(?P<user_login>.+)/quest/(?P<quest_id>[0-9]+)/$', views.UiUserQuestView.as_view(),
        name='quest'),
    url('^user/(?P<user_login>.+)/quest/$', views.UiNewQuestView.as_view(), name='newquest'),
    url('^user/(?P<user_login>.+)/place/(?P<place_id>[0-9]+)/puzzle/$', views.UiUserContributionPuzzle.as_view()),
    url('^user/(?P<user_login>.+)/place/(?P<place_id>[0-9]+)/fact/$', views.UiUserContributionFact.as_view()),
    url('^user/(?P<user_login>.+)/$', views.UiUserInfoView.as_view(), name='user'),
    url('^login1/$', views.UiLoginView.as_view(), name='login_ui'),
    url('^login/$', views.ApiLoginView.as_view(), name='login'),
    # url('^refresh/', views.RefreshView.as_view(), name='refresh'),
    # url('^oauth/', views.AuthView.as_view(), name='oauth'),
    url('^$', views.UiIndexView.as_view(), name='index'),
]

aggregator/service/models.py
from django.db import models

# Create your models here.

aggregator/service/views.py
import requests
import json

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from .service_methods import GetUserInfo, GetUserQuestInfo, PostUserQuest, GetPlaceInfo, PostNewQuest

client_id = 'we3iHS6Z8cfj7CDypvBLhNDtQHrsgjS1HSw5CGFm'
client_secret = 'KyIeQtuXyN2Vc4VMSTAXzuoNebNnk6UAWkcekE5P9wscnPM2EAa0TyZxSZDWc6PH6A179t3fDNXdICLUsBooXF4gmmRqWjixf6pvy3imF6bz3GuEHj9sXDKnjHMrOb8S'


class UiUserInfoView(View):
    # Get info about user, including his quests list
    def get(self, request, *args, **kwargs):
        user_login = kwargs.get('user_login')

        data = {
            'username': user_login,
            'token': request.COOKIES.get('uid_token', '')
        }
        res = requests.post('http://localhost:8010/user/token_check/', data=data)
        if res.status_code == 401:
            return HttpResponseRedirect(reverse('service:index'))

        res = GetUserInfo(request, user_login)

        data = json.loads(res.content.decode())

        if res.status_code == 200:
            result = render(request, 'service/userinfo.html', data)
        elif res.status_code == 404:
            result = render(request, 'service/404.html', data)
        elif res.status_code == 403:
            result = render(request, 'service/403.html', data)
        elif res.status_code == 503:
            result = render(request, 'service/503.html', data)
        else:
            result = res

        return result


class UiUserQuestView(View):
    # Get user's quest - progress
    def get(self, request, *args, **kwargs):
        user_login = kwargs.get('user_login')
        quest_id = kwargs.get('quest_id')

        data = {
            'username': user_login,
            'token': request.COOKIES.get('uid_token', '')
        }
        res = requests.post('http://localhost:8010/user/token_check/', data=data)
        if res.status_code == 401:
            return HttpResponseRedirect(reverse('service:index'))

        res = GetUserQuestInfo(quest_id, user_login)

        data = json.loads(res.content.decode())

        if res.status_code == 200:
            result = render(request, 'service/questinfo.html', data)
        elif res.status_code == 404:
            result = render(request, 'service/404.html', data)
        elif res.status_code == 503:
            result = render(request, 'service/503.html', data)
        else:
            result = res

        return result

    # Post user's answer - check if correct
    def post(self, request, *args, **kwargs):
        user_login = kwargs.get('user_login')
        quest_id = kwargs.get('quest_id')
        answer = request.POST.get('answer')

        data = {
            'username': user_login,
            'token': request.COOKIES.get('uid_token', '')
        }
        res = requests.post('http://localhost:8010/user/token_check/', data=data)
        if res.status_code == 401:
            return HttpResponseRedirect(reverse('service:index'))

        res = PostUserQuest(quest_id, request, user_login)

        data = json.loads(res.content.decode())

        if res.status_code == 200:
            result = render(request, 'service/questinfo.html', data)
        elif res.status_code == 404:
            result = render(request, 'service/404.html', data)
        elif res.status_code == 503:
            result = render(request, 'service/503.html', data)
        else:
            result = res

        return result


class UiPlaceInfoView(View):
    # see info about place - some fact
    def get(self, request, *args, **kwargs):
        user_login = kwargs.get('user_login')
        quest_id = kwargs.get('quest_id')
        place_id = kwargs.get('place_id')
        fact_id = kwargs.get('fact_id')

        data = {
            'username': user_login,
            'token': request.COOKIES.get('uid_token', '')
        }
        res = requests.post('http://localhost:8010/user/token_check/', data=data)
        if res.status_code == 401:
            return HttpResponseRedirect(reverse('service:index'))

        res = GetPlaceInfo(fact_id, place_id, quest_id, user_login)

        data = json.loads(res.content.decode())

        if res.status_code == 200:
            result = render(request, 'service/placefact.html', data)
        elif res.status_code == 404:
            result = render(request, 'service/404.html', data)
        elif res.status_code == 503:
            result = render(request, 'service/503.html', data)
        else:
            result = res

        return result


class UiNewQuestView(View):
    # Create new quest
    def post(self, request, *args, **kwargs):
        user_login = kwargs.get('user_login')

        data = {
            'username': user_login,
            'token': request.COOKIES.get('uid_token', '')
        }
        res = requests.post('http://localhost:8010/user/token_check/', data=data)
        if res.status_code == 401:
            return HttpResponseRedirect(reverse('service:index'))

        res = PostNewQuest(user_login)

        if res.status_code == 201:
            result = redirect('service:user', user_login)
        elif res.status_code == 404:
            data = json.loads(res.content.decode())
            result = render(request, 'service/404.html', data)
        elif res.status_code == 503:
            data = json.loads(res.content.decode())
            result = render(request, 'service/503.html', data)
        else:
            result = res

        return result


class UiUserContributionPuzzle(View):
    # todo in future
    pass


class UiUserContributionFact(View):
    # todo in future
    pass


class UiIndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'service/index.html')


class UiLoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'service/login.html')

    def post(self, request, *args, **kwargs):
        data = {
            "username": request.POST['login'],
            "password": request.POST['password'],
        }
        res = requests.post('http://localhost:8010/user/token/', data=data)
        if res.status_code == 403:
            return render(request, 'service/login.html', {'error': 'Неверный логин или пароль'})
        else:
            resp = render(request, 'service/login_ok.html', {'username': data['username']})
            resp.set_cookie('uid_token', res.json()['token'])
            return resp


class ApiLoginView(View):
    def get(self, request, *args, **kwargs):
        # return render(request, 'service/login.html')
        # return HttpResponseRedirect('http://localhost:8010/o/authorize/?response_type=code&'
        #                             'client_id={}&redirect_uri=http://localhost:8000/oauth/'.format(
        #                                 client_id))
        # return HttpResponseRedirect(reverse('service:user'))
        pass

    def post(self, request, *args, **kwargs):
        # username = request.COOKIES.get('username')
        username = request.POST['login']
        return HttpResponseRedirect(reverse('service:user', args=[username]))


'''
@method_decorator(csrf_exempt, name='dispatch')
class AuthView(View):
    def get(self, request, *args, **kwargs):
        code = request.GET.get('code')
        try:
            res = requests.post('http://localhost:8010/o/token/',
                                {'grant_type': 'authorization_code', 'code': code, 'redirect_uri': 'http://localhost:8000/oauth/'}, auth=(client_id, client_secret))
        except requests.exceptions.ConnectionError:
            data = res.json()
            return render(request, 'service/503.html', data)
        if res.status_code != 200:
            return res

        username = request.COOKIES.get('username')
        res1 = HttpResponseRedirect(reverse('service:user', args=[username]))
        # res1 = HttpResponse()
        res1.set_cookie('access_token', res.json()['access_token'])
        res1.set_cookie('refresh_token', res.json()['refresh_token'])

        return res1


@method_decorator(csrf_exempt, name='dispatch')
class RefreshView(View):
    def get(self, request, *args, **kwargs):
        try:
            res = requests.post('http://localhost:8010/o/token/?grant_type=refresh_token&client_id={}&'
                                'client_secret={}&refresh_token={}&redirect_uri=http://localhost:8000/oauth/'.format(
                                    client_id, client_secret, request.COOKIES['refresh_token']))
            # res = requests.post('http://localhost:8010/o/token/',
            #                     {'grant_type': 'refresh_token', 'refresh_token': request.COOKIES['refresh_token'],
            #                      'redirect_uri': 'http://localhost:8000/oauth/'}, auth=(client_id, client_secret))
        except requests.exceptions.ConnectionError:
            data = res.json()
            return render(request, 'service/503.html', data)
        if res.status_code != 200:
            return res

        res1 = HttpResponse()
        res1.set_cookie('access_token', res.json()['access_token'])
        res1.set_cookie('refresh_token', res.json()['refresh_token'])

        return res1
'''

aggregator/service/templates/service/503.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Error 503</title>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
    </head>
<body>
    <div class="alert alert-danger" role="alert">
        <strong>Error: </strong> {{ error }}
    </div>
</body>
</html>

aggregator/service/templates/service/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Квесты</title>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
    <style>
        body {
            background-image: linear-gradient(to right, yellowgreen, lightskyblue);
        }
    </style>
    </head>
<body>
    <h1 class="text-center">Добро пожаловать на сайт городских квестов!</h1>
    <div class="text-center">
        <a href="{% url 'service:login_ui' %}"
           class="btn btn-default text-center">Войти</a>
    </div>
</body>
</html>

aggregator/service/templates/service/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Квесты</title>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
    <style>
        body {
            background-image: linear-gradient(to right, yellowgreen, lightskyblue);
        }
    </style>
    </head>
<body>
    <div class="container-fluid">
       <div class="row-fluid">
            <div class="centering text-center">
                <div class="col-md-offset-5 col-md-3">
                    <form class="form-login" id="login_form" method="post" action="{% url 'service:login_ui' %}">
                    {% csrf_token %}
                    <h4>Введите логин и пароль</h4>
                    <input type="text" id="login" name="login" class="form-control input-sm chat-input" placeholder="логин" required/>
                    </br>
                    <input type="password" id="password" name="password" class="form-control input-sm chat-input" placeholder="пароль" required/>
                    </br>
                    <div class="wrapper">
                    <span class="group-btn">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
                    </span>
                    </div>
                    </form>
                    <div class="row-fluid">
                    <p class="text-danger">{{ error }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

aggregator/service/templates/service/login_ok.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Квесты</title>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
    <style>
        body {
            background-image: linear-gradient(to right, yellowgreen, lightskyblue);
        }
    </style>
    </head>
<body>
    <h1 class="text-center">Успех</h1>
    <div class="text-center">
        <a href="{% url 'service:user' username %}">
            Мои квесты
        </a>
    </div>
</body>
</html>

aggregator/service/templates/service/placefact.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Квесты</title>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
    <style>
        body {
            background-image: linear-gradient(to right, yellowgreen, lightskyblue);
        }
    </style>
    </head>
<body>
    <h1 class="text-center">{{ user.name }}</h1>
    <h4 class="text-center" style="color:grey">(@{{ user.login }})</h4>
    <div class="container">
        <div class="row">
            <h4>Квест №{{ quest.id }}</h4>
        </div>
        <div class="row">
            <h4>Место: {{ place.name }}</h4>
        </div>
        <div class="row">
            <h4>Интересный факт:</h4>
            <br>
            <div class="col-sm-12">
                {{ puzzle.text }}
            </div>
        </div>
    </div>
</body>
</html>

aggregator/service/templates/service/questinfo.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Квесты</title>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
    <style>
        body {
            background-image: linear-gradient(to right, yellowgreen, lightskyblue);
        }
    </style>
    </head>
<body>
    <h1 class="text-center">{{ user.name }}</h1>
    <h4 class="text-center" style="color:grey">(@{{ user.login }})</h4>
    <h2 class="text-center">
        Квест №{{ quest.id }}
    </h2>
    <div class="container">
        {% if quest.completed == 'False' %}
        <div class="row">
            <h4>Задание №{{ quest.cur_task }}</h4>
            <div class="col-sm-12">
                {{ puzzle.text }}
            </div>
        </div>
        <div class="row">
            {% if guess != 'checking' %}
            <div class="col-sm-6">
                <form class="form-signin" id="answer_form" method="post"
                      action="{% url 'service:quest' user.login quest.id %}">
                  {% csrf_token %}

                  <br>
                  <input type="text" name="answer" class="form-control" placeholder="Ваш ответ" value="" required autofocus>
                  <br>
                  <button class="btn btn-lg btn-primary btn-block" type="submit">Отправить</button>
                </form>
            </div>
            {% endif %}
        </div>
            {% if guess == 'checking' %}
            <br>
            <p>
                Ваш ответ отправлен на проверку
            </p>
            <a href="{% url 'service:quest' user.login quest.id %}">
                Нажмите, чтобы обновить страницу
            </a>
            {% endif %}
        {% else %}
        <div class="row">
            <h4>Вы прошли этот квест</h4>
        </div>
        {% endif %}
        <div class="row">
            <a href="{% url 'service:user' user.login%}">Вернуться к списку</a>
        </div>
    </div>
</body>
</html>

aggregator/service/templates/service/userinfo.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Квесты</title>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
    <style>
        body {
            background-image: linear-gradient(to right, yellowgreen, lightskyblue);
        }
    </style>
    </head>
<body>
    <h1 class="text-center">{{ name }}</h1>
    <h4 class="text-center" style="color:grey">(@{{ login }})</h4>
    <div class="container">
        <div class="row">
            <div class="pull-right">
                <form class="form-row" id="new_quest_form" method="post"
                      action="{% url 'service:newquest' login %}">
                  {% csrf_token %}
                  <button class="btn btn-lg btn-primary btn-block" type="submit">
                      <span class="glyphicon glyphicon-plus"></span>
                      Добавить новый квест
                  </button>
                </form>
            </div>
        </div>
        {% if quests %}
            <h4>Ваши квесты</h4>
            {% if not 'unavailable' in quests %}
            <div class="row">
                <div class="col-sm-2">
                    {% for quest in quests %}
                    <a href="{% url 'service:quest' login quest.pk %}" class="list-group-item">
                        Квест №{{ quest.pk }}
                        {% if quest.fields.completed %}
                        <span class="glyphicon glyphicon-ok"></span>
                        {% endif %}
                    </a>
                    {% endfor %}
                </div>
            </div>
            <div class="row pagination">
                <span class="step-links">
                    {% if pagination.has_previous %}
                        <a href="?page=1">&laquo; первая</a>
                        <a href="?page={{ pagination.previous_page_number }}">предыдущая</a>
                    {% endif %}

                    <span class="current">
                        Страница {{ pagination.number }} из {{ pagination.num_pages }}.
                    </span>

                    {% if pagination.has_next %}
                        <a href="?page={{ pagination.next_page_number }}">следующая</a>
                        <a href="?page={{ pagination.num_pages }}">последняя &raquo;</a>
                    {% endif %}
                </span>
            </div>
            {% else %}
            <p class="text-danger">{{ quests }}</p>
            {% endif %}
        <div class="row">
            <p>
                Пройдено: {{ quests_completed }} из {{ quests_number }}
            </p>
        </div>
        {% else %}
        <div class="row">
            <h4>У вас нет квестов</h4>
        </div>
        {% endif %}
    </div>
</body>
</html>